---
version: '3'
services:
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timeframe 5m 15m 1h 1d
      --timerange ${START_DATE:-20220101}-${END_DATE:-20220201}
      --config user_data/data/pairlists.json
      --datadir user_data/data/${EXCHANGE:-kucoin}
      --config user_data/data/dataformat_json.json
      --config user_data/data/pairlist_150.json
#      --days 200
#      --config user_data/data/kucoin-usdt-static.json
