---
version: '3'
services:
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timeframe 5m 15m 1h 1d
      --config user_data/data/main.json
      --datadir user_data/data/${EXCHANGE:-kucoin}
      --config user_data/data/dataformat_gz.json
      --config user_data/data/pairlist_160.json
      --days 30
#      --timerange ${START_DATE:-20220101}-${END_DATE:-20220201}
#      --config user_data/data/pairlist_test.json
#      --config user_data/data/kucoin-usdt-static.json
