---
version: '3'
services:
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timerange ${START_DATE:-20200101}-${END_DATE:-20220201}
      --timeframe 5m 15m 1h 1d
      --datadir user_data/data/${EXCHANGE:-kucoin}
      --config user_data/data/pairlist_150.json
      --config user_data/data/${EXCHANGE:-kucoin}-usdt-static.json
